services:
  emqx:
    image: emqx/emqx:latest
    container_name: emqx
    ports:
      - "1883:1883"
      - "18083:18083"
    environment:
      - EMQX_MQTT__WILDCARD_SUBSCRIPTION=true
    volumes:
      - ./emqx/acl.conf:/opt/emqx/etc/acl.conf:ro

  flow-lab-producer:
    build:
      context: .
      dockerfile: flow-lab-producer/Dockerfile
    container_name: flow-lab-producer
    restart: always
    depends_on:
      - emqx
    environment:
      MQTT_HOST: emqx
      MQTT_PORT: 1883

  flow-lab-consumer-producer:
    build:
      context: .
      dockerfile: flow-lab-consumer-producer/Dockerfile
    container_name: flow-lab-consumer-producer
    restart: always
    depends_on:
      - emqx
    environment:
      MQTT_HOST: emqx
      MQTT_PORT: 1883
      IN_TOPIC: lab/flow/in
      OUT_TOPIC: lab/flow/out
      DROP_EVERY_N: 0

  flow-lab-consumer:
    build:
      context: .
      dockerfile: flow-lab-consumer/Dockerfile
    container_name: flow-lab-consumer
    restart: always
    depends_on:
      - emqx
    environment:
      MQTT_HOST: emqx
      MQTT_PORT: 1883
      IN_TOPIC: lab/flow/out
      WS_CHANNEL: ws/live/out
    ports:
      - "8090:8090"

#  system-flow-investigator:
#    build:
#      context: .
#      dockerfile: system-flow-investigator/Dockerfile
#    container_name: system-flow-investigator
#    restart: always
#    depends_on:
#      - emqx
#    environment:
#      MQTT_HOST: emqx
#      MQTT_PORT: 1883
#      MQTT_TOPIC_FILTER: lab/flow/#
